# Generated by Django 5.0.4 on 2024-04-06 21:06

import django.db.models.deletion
import mapApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0011_vote_unique_voter_property_value_combination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emailConfirmed',
            new_name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expiration_date',
            field=models.DateField(default=mapApp.models.get_default_now_my_datetime),
        ),
        migrations.AddField(
            model_name='project',
            name='job_flexibility',
            field=models.CharField(choices=[('AT_WORK', 'Présentiel'), ('HYBRID', 'Hybride'), ('FROM_HOME', 'Télétravail')], default='AT_WORK', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('PART_TIME', 'Temps partiel'), ('FULL_TIME', 'Temps plein'), ('CONTRACT', 'Contrat')], default='FULL_TIME', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='starting_date',
            field=models.DateField(default=mapApp.models.get_default_my_datetime),
        ),
        migrations.AddField(
            model_name='property',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propertyFromUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propertyOwnerFromUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectFromUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
