# Generated by Django 5.0.4 on 2024-04-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0012_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expiration_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='starting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
