# Generated by Django 5.0.4 on 2024-04-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0013_alter_project_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
