# Generated by Django 5.0.4 on 2024-04-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0014_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
