# Generated by Django 5.0.4 on 2024-04-10 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0018_property_description_alter_project_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
