# Generated by Django 5.0.4 on 2024-04-12 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0020_follow_updated_project_updated_property_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyFromJob', to='mapApp.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyFromUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveFromJob', to='mapApp.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveFromUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SaveApplyjob',
        ),
        migrations.AddConstraint(
            model_name='applyjob',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_apply_job_combination'),
        ),
        migrations.AddConstraint(
            model_name='savejob',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_save_job_combination'),
        ),
    ]
