# Generated by Django 5.0.4 on 2024-04-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0021_applyjob_savejob_delete_saveapplyjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyFromJob', to='mapApp.project'),
        ),
        migrations.AlterField(
            model_name='savejob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveFromJob', to='mapApp.project'),
        ),
    ]
