# Generated by Django 5.0.4 on 2024-04-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0024_rename_street_property_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenity',
        ),
    ]
