# Generated by Django 5.0.4 on 2024-04-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0025_remove_property_amenity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='housenumber',
            new_name='house_number',
        ),
    ]
