# Generated by Django 5.0.4 on 2024-04-22 16:47

import mapApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0026_rename_housenumber_property_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[mapApp.models.validate_password_length], verbose_name='password'),
        ),
    ]
